
{{-- Classi per ottimizzazione post-css in produzione --}}

<div class="
    bg-sigred-darkest
    bg-seablue-darkest
    bg-fcyellow-darkest
    bg-sssegreen-darkest
    bg-sssebackground-darkest
    bg-sigred-dark
    bg-seablue-dark
    bg-fcyellow-dark
    bg-sssegreen-dark
    bg-sssebackground-dark
    bg-sigred
    bg-seablue
    bg-fcyellow
    bg-sssegreen
    bg-sssebackground
    bg-sigred-light
    bg-seablue-light
    bg-fcyellow-light
    bg-sssegreen-light
    bg-sssebackground-light
    bg-sigred-lightest
    bg-seablue-lightest
    bg-fcyellow-lightest
    bg-sssegreen-lightest
    bg-sssebackground-lightest

    hover:bg-sigred-darkest
    hover:bg-seablue-darkest
    hover:bg-fcyellow-darkest
    hover:bg-sssegreen-darkest
    hover:bg-sssebackground-darkest
    hover:bg-sigred-dark
    hover:bg-seablue-dark
    hover:bg-fcyellow-dark
    hover:bg-sssegreen-dark
    hover:bg-sssebackground-dark
    hover:bg-sigred
    hover:bg-seablue
    hover:bg-fcyellow
    hover:bg-sssegreen
    hover:bg-sssebackground
    hover:bg-sigred-light
    hover:bg-seablue-light
    hover:bg-fcyellow-light
    hover:bg-sssegreen-light
    hover:bg-sssebackground-light
    hover:bg-sigred-lightest
    hover:bg-seablue-lightest
    hover:bg-fcyellow-lightest
    hover:bg-sssegreen-lightest
    hover:bg-sssebackground-lightest

    text-sigred-darkest
    text-seablue-darkest
    text-fcyellow-darkest
    text-sssegreen-darkest
    text-sssebackground-darkest
    text-sigred-dark
    text-seablue-dark
    text-fcyellow-dark
    text-sssegreen-dark
    text-sssebackground-dark
    text-sigred
    text-seablue
    text-fcyellow
    text-sssegreen
    text-sssebackground
    text-sigred-light
    text-seablue-light
    text-fcyellow-light
    text-sssegreen-light
    text-sssebackground-light
    text-sigred-lightest
    text-seablue-lightest
    text-fcyellow-lightest
    text-sssegreen-lightest
    text-sssebackground-lightest

    hover:text-sigred-darkest
    hover:text-seablue-darkest
    hover:text-fcyellow-darkest
    hover:text-sssegreen-darkest
    hover:text-sssebackground-darkest
    hover:text-sigred-dark
    hover:text-seablue-dark
    hover:text-fcyellow-dark
    hover:text-sssegreen-dark
    hover:text-sssebackground-dark
    hover:text-sigred
    hover:text-seablue
    hover:text-fcyellow
    hover:text-sssegreen
    hover:text-sssebackground
    hover:text-sigred-light
    hover:text-seablue-light
    hover:text-fcyellow-light
    hover:text-sssegreen-light
    hover:text-sssebackground-light
    hover:text-sigred-lightest
    hover:text-seablue-lightest
    hover:text-fcyellow-lightest
    hover:text-sssegreen-lightest
    hover:text-sssebackground-lightest

    border-sigred-darkest
    border-seablue-darkest
    border-fcyellow-darkest
    border-sssegreen-darkest
    border-sssebackground-darkest
    border-sigred-dark
    border-seablue-dark
    border-fcyellow-dark
    border-sssegreen-dark
    border-sssebackground-dark
    border-sigred
    border-seablue
    border-fcyellow
    border-sssegreen
    border-sssebackground
    border-sigred-light
    border-seablue-light
    border-fcyellow-light
    border-sssegreen-light
    border-sssebackground-light
    border-sigred-lightest
    border-seablue-lightest
    border-fcyellow-lightest
    border-sssegreen-lightest
    border-sssebackground-lightest

    hover:border-sigred-darkest
    hover:border-seablue-darkest
    hover:border-fcyellow-darkest
    hover:border-sssegreen-darkest
    hover:border-sssebackground-darkest
    hover:border-sigred-dark
    hover:border-seablue-dark
    hover:border-fcyellow-dark
    hover:border-sssegreen-dark
    hover:border-sssebackground-dark
    hover:border-sigred
    hover:border-seablue
    hover:border-fcyellow
    hover:border-sssegreen
    hover:border-sssebackground
    hover:border-sigred-light
    hover:border-seablue-light
    hover:border-fcyellow-light
    hover:border-sssegreen-light
    hover:border-sssebackground-light
    hover:border-sigred-lightest
    hover:border-seablue-lightest
    hover:border-fcyellow-lightest
    hover:border-sssegreen-lightest
    hover:border-sssebackground-lightest

    dark:border-sigred-darkest
    dark:border-seablue-darkest
    dark:border-fcyellow-darkest
    dark:border-sssegreen-darkest
    dark:border-sssebackground-darkest
    dark:border-sigred-dark
    dark:border-seablue-dark
    dark:border-fcyellow-dark
    dark:border-sssegreen-dark
    dark:border-sssebackground-dark
    dark:border-sigred
    dark:border-seablue
    dark:border-fcyellow
    dark:border-sssegreen
    dark:border-sssebackground
    dark:border-sigred-light
    dark:border-seablue-light
    dark:border-fcyellow-light
    dark:border-sssegreen-light
    dark:border-sssebackground-light
    dark:border-sigred-lightest
    dark:border-seablue-lightest
    dark:border-fcyellow-lightest
    dark:border-sssegreen-lightest
    dark:border-sssebackground-lightest

    dark:hover:border-sigred-darkest
    dark:hover:border-seablue-darkest
    dark:hover:border-fcyellow-darkest
    dark:hover:border-sssegreen-darkest
    dark:hover:border-sssebackground-darkest
    dark:hover:border-sigred-dark
    dark:hover:border-seablue-dark
    dark:hover:border-fcyellow-dark
    dark:hover:border-sssegreen-dark
    dark:hover:border-sssebackground-dark
    dark:hover:border-sigred
    dark:hover:border-seablue
    dark:hover:border-fcyellow
    dark:hover:border-sssegreen
    dark:hover:border-sssebackground
    dark:hover:border-sigred-light
    dark:hover:border-seablue-light
    dark:hover:border-fcyellow-light
    dark:hover:border-sssegreen-light
    dark:hover:border-sssebackground-light
    dark:hover:border-sigred-lightest
    dark:hover:border-seablue-lightest
    dark:hover:border-fcyellow-lightest
    dark:hover:border-sssegreen-lightest
    dark:hover:border-sssebackground-lightest
"></div>